include_recipe '../cookbooks/base/default.rb'
include_recipe '../cookbooks/users/default.rb'
include_recipe '../cookbooks/dotfiles/default.rb'
include_recipe '../cookbooks/vim/default.rb'
include_recipe '../cookbooks/ruby/default.rb'
include_recipe '../cookbooks/kernel-build/default.rb'
