# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

node = YAML.load_file('../../devenv-nodes/dormouse-001.yml')

Vagrant.configure(2) do |config|
  config.vm.box = 'terrywang/archlinux'

  config.ssh.username = node['user']['name']
  config.ssh.private_key_path = node['user']['privatekey']

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 2
    vb.memory = '2048'
  end
end
